from file_lib import game_ops

#An example usage of some of the functions from the game_ops class in the
#file_lib.py

game = game_ops()
#game.new_game()
if game.load_game():
    items = ["boat paddle"]
    print("\nRoom title and description")
    print(game.get_room_title())
    print(game.get_room_desc())
    print("\nTry to move to Cave")
    print(game.attempt_move("cave", items))
    print("\nTry to move to game trail")
    print(game.attempt_move("game trail", items))
    print("\nTry to move West")
    print(game.attempt_move("w", items))
    print("\nLookat a rescue whistle")
    print(game.verb("Rescue Whistle", "lookat", False))
    print("\nTry to Move to Ranger Station")
    print(game.attempt_move("ranger station", items))
    print("\nTry to Move to Game Trail")
    print(game.attempt_move("game trail", items))
    print("\nUse the lantern twice, that is in player inventory!")
    print(game.verb("lantern", "use", True))
    print(game.verb("lantern", "use", True))
    print("\nUse a pickaxe that does not exist, first time with 'use' and then 'toss'")
    print(game.verb("pickaxe", "use", False))
    print(game.verb("pickaxe", "toss", False))
    print("\nlookat the lantern in the inventory")
    print(game.verb("lantern", "lookat", True))
    print("\nLookat feature 1")
    print(game.verb("feature_1_title", "lookat", False))
    print("\nLookat feature 2")
    print(game.verb("feature_2_title", "lookat", False))
    print("\nLookat rescue whistle")
    print(game.verb("rescue whistle", "lookat", False))
    print("\nLookat Dusty old map")
    print(game.verb("dusty old map", "lookat", False))
