items = {
    "boat paddle": "boat paddle", 
    "can opener": "can opener", 
    "can of sweetened condensed milk": "can of sweetened condensed milk", 
    "dusty old map": "dusty old map", 
    "flare gun": "flare gun", 
    "frozen dead hare": "frozen dead hare", 
    "heavy winter parka": "heavy winter parka", 
    "lantern": "lantern", 
    "rescue whistle": "rescue whistle", 
    "tattered notebook": "tattered notebook", 
    "map": "dusty old map", 
    "oar": "boat paddle", 
    "paddle": "boat paddle"
}
rooms = {
    "camp": "camp", 
    "cave": "cave", 
    "crash": "crash site", 
    "crash site": "crash site", 
    "dense brush": "dense brush", 
    "field": "field", 
    "fire tower": "fire tower", 
    "game trail": "game trail", 
    "mountain ascent": "mountain ascent", 
    "mountain base": "mountain base", 
    "mountain summit": "mountain summit", 
    "ranger station": "ranger station", 
    "rapids": "rapids", 
    "river": "river", 
    "shore": "shore", 
    "shoreline": "shore", 
    "site": "crash site", 
    "waterfall": "waterfall", 
    "woods": "woods", 
    "accident": "crash site", 
    "campsite": "camp", 
    "coast": "shore", 
    "crash": "crash site", 
    "edge of lake": "shore", 
    "shore": "shore", 
    "shoreline": "shore", 
    "site": "crash site"
}
actions = {
    "eat": "eat", 
    "go": "go", 
    "help": "help", 
    "ingest": "eat", 
    "inventory": "inventory", 
    "look": "look", 
    "look at": "look at", 
    "pull": "pull", 
    "read": "read", 
    "search": "search", 
    "take": "take", 
    "use": "use"
}
all_words = {"help": "help", "rapids": "rapids", "campsite": "camp", "site": "crash site", "can of sweetened condensed milk": "can of sweetened condensed milk", "woods": "woods", "go": "go", "crash": "crash site", "flare gun": "flare gun", "take": "take", "use": "use", "field": "field", "cave": "cave", "crash site": "crash site", "paddle": "boat paddle", "eat": "eat", "can opener": "can opener", "oar": "boat paddle", "tattered notebook": "tattered notebook", "mountain summit": "mountain summit", "ranger station": "ranger station", "map": "dusty old map", "look at": "look at", "shoreline": "shore", "dense brush": "dense brush", "read": "read", "dusty old map": "dusty old map", "rescue whistle": "rescue whistle", "search": "search", "coast": "shore", "waterfall": "waterfall", "heavy winter parka": "heavy winter parka", "boat paddle": "boat paddle", "pull": "pull", "frozen dead hare": "frozen dead hare", "accident": "crash site", "look": "look", "mountain ascent": "mountain ascent", "inventory": "inventory", "camp": "camp", "game trail": "game trail", "ingest": "eat", "edge of lake": "shore", "fire tower": "fire tower", "shore": "shore", "mountain base": "mountain base", "river": "river", "lantern": "lantern"}