import json
import os

MASTER_WORDS_FILENAME = "master_words.py"
ITEMS_FILENAME = "items_dict"
ROOMS_FILENAME = "rooms_dict"
VERBS_FILENAME = "verbs_dict"

def update_master_words():
    """
    Updates the master_words.py file with the contents of individual items,
    rooms, and verbs files generated by the data module. In addition to
    including individual dicts containing the items, rooms, and verbs,
    master_words.py includes an 'all_words' dict that contains all of the
    key-value pairs from those individual dicts
    """
    # Start by removing the existing copy of master_words.py
    os.remove(MASTER_WORDS_FILENAME)
    data_dir = os.path.abspath('../data')
    items_full_path = os.path.join(data_dir, ITEMS_FILENAME)
    rooms_full_path = os.path.join(data_dir, ROOMS_FILENAME)
    verbs_full_path = os.path.join(data_dir, VERBS_FILENAME)
    # Copy the contents of the source files into their own dicts.
    with open(MASTER_WORDS_FILENAME, "a") as master_file:
        with open(items_full_path, "r") as items_file:
            items_dict_str = items_file.read()
            master_file.write("items = " + items_dict_str.lower() + "\n")
        with open(rooms_full_path, "r") as rooms_file:
            rooms_dict_str = rooms_file.read()
            master_file.write("rooms = " + rooms_dict_str.lower() + "\n")
        with open(verbs_full_path, "r") as verbs_file:
            verbs_dict_str = verbs_file.read()
            master_file.write("actions = " + verbs_dict_str.lower() + "\n")
        # Make a master dict with the words from all the dicts.
        # At this stage, the dicts are actually strings, so they must be
        # converted to dicts before calling update().
        all_words = {}
        items_dict = json.loads(items_dict_str.lower())
        all_words.update(items_dict)
        rooms_dict = json.loads(rooms_dict_str.lower())
        all_words.update(rooms_dict)
        verbs_dict = json.loads(verbs_dict_str.lower())
        all_words.update(verbs_dict)
        all_words_str = json.dumps(all_words)
        master_file.write("all_words = " + all_words_str)

if __name__ == "__main__":
    update_master_words()

# Resources used in writing this script:
# https://stackoverflow.com/questions/3758866/python-get-path-to-file-in-sister-directory
# https://stackoverflow.com/questions/7132861/building-full-path-filename-in-python
# http://www.pythonforbeginners.com/files/reading-and-writing-files-in-python
# https://stackoverflow.com/questions/38987/how-to-merge-two-dictionaries-in-a-single-expression
# https://stackoverflow.com/questions/988228/convert-a-string-representation-of-a-dictionary-to-a-dictionary